# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-25 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20191225_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelembaban',
            name='tanggal',
            field=models.DateField(blank=True, unique=True),
        ),
    ]
